// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcp7l5I4ftPHAp6F6CMPR3pzRbNVx9dRw',
    appId: '1:259953238721:web:cdff9688f9f47ed8856a40',
    messagingSenderId: '259953238721',
    projectId: 'bhbgroup-ed1bc',
    authDomain: 'bhbgroup-ed1bc.firebaseapp.com',
    storageBucket: 'bhbgroup-ed1bc.firebasestorage.app',
    measurementId: 'G-XNG88H4BGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIVy7q8xOd5RK1tqPCHe4OJC3YiFCFt8',
    appId: '1:259953238721:android:9154d21951d4aa1f856a40',
    messagingSenderId: '259953238721',
    projectId: 'bhbgroup-ed1bc',
    storageBucket: 'bhbgroup-ed1bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABMf50ia6zOcywhXXeTgzoFVtQ7E45LnM',
    appId: '1:259953238721:ios:8fd0bcf4329fde02856a40',
    messagingSenderId: '259953238721',
    projectId: 'bhbgroup-ed1bc',
    storageBucket: 'bhbgroup-ed1bc.firebasestorage.app',
    iosBundleId: 'com.example.appBhb',
  );
}
